resources:
  - name: source
    type: git
    source:
      uri: https://github.com/wilkinsona/spring-boot
      branch: build-restructure
jobs:
  - name: spring-boot-build
    public: true
    plan:
    - get: source
      trigger: true
      params:
        source:
          paths:
            - spring-boot-build
            - config/ci
    - task: build
      file: source/config/ci/spring-boot-build.yml
      params:
      - DEPLOY_USERNAME: {{deploy_username}}
      - DEPLOY_PASSWORD: {{deploy_password}}
  - name: spring-boot-tools
    public: true
    plan:
    - get: source
      trigger: true
      params:
        source:
          paths:
            - spring-boot-tools
            - config/ci
      passed:
        - spring-boot-build
      trigger: true
    - task: build
      file: source/config/ci/spring-boot-tools.yml
  - name: spring-boot-core
    public: true
    plan:
    - get: source
      trigger: true
      params:
        source:
          paths:
            - spring-boot-core
            - config/ci
      passed:
        - spring-boot-tools
      trigger: true
    - task: build
      file: source/config/ci/spring-boot-core.yml