---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: git-spring-boot-build

run:
  path: git-spring-boot-build/config/ci/spring-boot-build.sh