---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: source-spring-boot-build

run:
  path: source-spring-boot-build/config/ci/spring-boot-build.sh