---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: source-spring-boot-core

run:
  path: source-spring-boot-core/config/ci/spring-boot-core.sh